### ISSUE TITLE
Uploading Project Zip 

### ISSUE THREAD

**Issue by shapley** [gisquick/gisquick#125]
Had to upload a another project because the gisquick server lost the layers. Trying to upload the 'gisquick.zip' file which gets half way then produces the error attached. The two projects I have on the public server has had the same issue. 
![gisquick-upload-error](https://user-images.githubusercontent.com/7022885/133262053-60ace1dc-450f-4408-b21a-1e5c8e89dd0c.png)

**Comment by marcel-dancak** [comment]
And what is the size of your zip file? Current configuration should allow up to 75MB zip file. If that will be the reason, upload could be improved by checking limit before starting upload. I'm just not sure if its worth to do, because official plugin should be obsolete in the near future. This plugin requires to upload whole project on every change, which is not optimal.

**Comment by shapley** [comment]
H Marcel,

You were right the size of the project was over 75mb. I have reuploaded the project but maps and symbols won't display anymore. Nothing has changed in the project. 
![gisquick-failedrendering](https://user-images.githubusercontent.com/7022885/133389936-e9d1f45d-56a5-4a8f-acc0-525cc980a799.png)
![gisquick-legend](https://user-images.githubusercontent.com/7022885/133389978-1d25dde2-a73d-432b-b9c6-6e27e2ded3a3.png)

**Comment by marcel-dancak** [comment]
There was a problem with qgis server, now it should work.

I have upgraded qgis server few days ago, and I also did a few other changes in infrastructure. It seems that in current deployment, when some critical error occur in qgis service, even if it will be restarted, our gateway doesn't reconnect with restarted qgis server. I'll try to find some solution.

**Comment by shapley** [comment]
Thank You Marcel...We appreciate it and it is all working now. Many thanks once again!
