### ISSUE TITLE
Project server

### ISSUE THREAD

**Issue by shapley** [gisquick/gisquick#127]
Hi,

Noticed that the main projects page is down today. Is the project still active or been pulled?

[](https://projects.gisquick.org/)
[](https://projects.gisquick.org/?PROJECT=tetrahedra/gisquick/WyeUskCatchment_GISQUICK)

![gisquick](https://user-images.githubusercontent.com/7022885/139667465-01376c1b-a88c-4515-9197-9ab854384c9a.png)

**Comment by marcel-dancak** [comment]
Hi Paul,

I can see some timeout errors in recent logs, but right now the server works fine. It looks like there was and issue with mapcache caused by stale file locks. With current server application written in Django it's quite easy to block whole application, even if problem occur in one small part. This is also a reason why I'm currently rewriting server from scratch. Unfortunately this also means, that new planned Gisquick server will not going to be ready in the near time, but it's really necessary to do bunch of redesigns in order to provide better platform.

**Comment by shapley** [comment]
Thanks Marcel...I can see it is now back up. Thank you for your quick response.
