### ISSUE TITLE
KeyError: 'format' when using Gisquick plugin in QGIS 3.4.5

### ISSUE THREAD

**Issue by CYRDUB** [gisquick/gisquick#79]
Hello,

I'm new to Gisquick and tried to publish my first project. However I keep on encountering the same error message when trying to move to the topics page in the publication process.

See picture for a screenshot of the error message.

![image](https://user-images.githubusercontent.com/57090318/67664878-cba4c900-f968-11e9-8522-66e173c83e38.png)

**Comment by marcel-dancak** [comment]
Hi,

it seems to be a problem of gathering information from some WMS layer, where plugin expect to find information about image format for GetMap requests. This part is quite tricky because of high number of possible layer types and differences in their metadata. But at least we could make it crash with more information about particular layer for easier troubleshooting.
Thank you for your report, we will try to address this issue in future release.

**Comment by CYRDUB** [comment]
Hello Marcel,

Thanks for your feedback. In this case it turns out the issue were the XYZ
tile layers in my QGIS project (more specifically for OSM and ESRI
Satellite).
I was able to run the plugin after removing these layers from my project
(not selecting them in the plugin wasn't sufficient).

However I have now encountered another issue. When I upload the zip file to
Gisquick the map is not rendering (no information displayed whatsoever). Do
you have any idea what might be the cause of this issue?

Br,

Cyrille

**Comment by marcel-dancak** [comment]
Hi Cyrille,

I think you have already deleted your project so I'm not able to check it. But in last few days I have noticed several times problems with mapserver, probably caused by overloading. When it happens, it returns blank images, without error. And restart of qgis mapserver is needed to make it work properly again. So maybe you just tried your project during such period, or it was caused by something else. It's hard to tell without more info, which is caused by not very good logging in Gisquick. But this may change in near future.
